name: Moj Prvi Workflow
on:
push:
branches: [ &quot;main&quot; ]
pull_request:
branches: [ &quot;main&quot; ]
jobs:
pozdrav:
runs-on: ubuntu-latest
steps:
- name: Checkout koda
uses: actions/checkout@v4
- name: Ispisi pozdrav
run: echo &quot;Zdravo iz GitHub Actions!&quot;
- name: Pokazi datum i vrijeme
run: date
- name: Pokazi strukturu fajlova
run: ls -la
